### ISSUE TITLE
Illegal Key After completing Google Sign in

### ISSUE THREAD

**Issue by p1utoze** [chrisK824/fastapi-sso-example#79]
Hi! I wanted to try this project and followed the instructions to setup.
I am running the FastAPI on port 8000
This is my `.env` file:
```
HOST=http://localhost:8000
OAUTHLIB_INSECURE_TRANSPORT=1
DATABASE_URL=sqlite:///db.sqlite3
...
GOOGLE_CLIENT_ID=<REDACTED>
GOOGLE_CLIENT_SECRET=<REDACTED>
```
Once after I complete the Google OAuth flow, The callback route returns this message with Status Code 500 Internal Server Error:
```
{
  "detail": "An unexpected error occurred. Report this message to support: Illegal key ''"
}
```

I am unable to fix this issue. Does anyone else face this or is it just me?

**Comment by chrisK824** [comment]
Hey @p1utoze , can you add some more info by removing that try catch block there or an extra logging to show the full traceback?

**Comment by chrisK824** [comment]
Hey @p1utoze any news on that? Have you sorted out arter all? Could I close this issue?

**Comment by p1utoze** [comment]
> Hey @p1utoze any news on that? Have you sorted out arter all? Could I close this issue?

Hi @chrisK824 apologies for the late response . The error was due to the empty `COOKIE_NAME` variable in .env. i resolved this issue. Thanks
